### ISSUE TITLE
Ejabberd 17.04 unknown option 'auth_opts' will be likely ignored

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [processone/ejabberd-contrib#210] opened 2017-04-17 11:23 UTC
Hi,|
I have installed Ejabberd 17.04 and installed **ejabberd_auth_http** module and followed the instructions specified [here](https://github.com/processone/ejabberd-contrib/tree/master/ejabberd_auth_http)

But it does not pick up the auth_opts and said its unknown. Here is my configuration
```
auth_method: http
auth_opts:
  host: "http://localhost:9095"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```
Here is the error message:
**unknown option 'auth_opts' will be likely ignored**

Can someone tell me the issue here?

**Comment by Sharpek** [comment] 2017-04-18 08:25
I have same problem.

**Comment by badlop** [comment] 2017-04-19 11:13
Duplicate of #211

**Closed by badlop** 2017-04-19 11:13 UTC

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-19 11:15
Does anyone suggest a possible fix for this?
