### ISSUE TITLE
ejabberd_auth_http unknown option 'auth_opts' will be likely ignored

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [processone/ejabberd-contrib#211] opened 2017-04-19 07:04 UTC
I am running latest **ejabberd 17.04** and using **ejabberd_auth_http** module
Here is my configuration

```
auth_method: http
auth_opts:
  host: "http://localhost:9095"
  connection_pool_size: 10
  connection_opts: []
  basic_auth: ""
  path_prefix: "/"
```

Here is the error that i am getting

> 2017-04-19 11:45:12.970 [error] <0.635.0>@ejabberd_config:validate_opts:1012 unknown option 'auth_opts' will be likely ignored

Can you tell me is this module working on ejabberd 17.04? if its not working is there any alternative that i can use for now?

**Comment by prefiks** [comment] 2017-04-19 07:57
Please update your version ejabberd_auth_http, latest version won't have that problem.

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-19 11:14
@prefiks It does not work on ejabberd 17.04

**Comment by badlop** [comment] 2017-04-19 11:23
Problem confirmed, because https://github.com/processone/ejabberd/commit/fadcc85553e2fa00c26233e36c0808f5d0089876 introduced relevant changes in the start code, and may need another fix.

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-19 13:42
Thanks @badlop for confirmation. 
Any idea when it will be resolved? 
I am ready to help in anyway

**Comment by badlop** [comment] 2017-04-19 14:47
I've written a preliminary patch. It ensures modules binaries coming from ext_mod are loaded before reading the configuration file. But in my test, auth_http doesn't start correctly. It may be because I configured it with dummy configuration options, or this patch introduces a bug, or there is another bug.

Anyway, can you try it? Does it allow ejabberd_auth_http to work?
```diff
--- a/src/ejabberd_app.erl
+++ b/src/ejabberd_app.erl
@@ -48,6 +48,7 @@ start(normal, _Args) ->
     ejabberd:check_app(ejabberd),
     db_init(),
     setup_if_elixir_conf_used(),
+    ext_mod:pre_start(),
     ejabberd_config:start(),
     set_settings_from_config(),
     file_queue_init(),
diff --git a/src/ext_mod.erl b/src/ext_mod.erl
index 6ca218c..45cc236 100644
--- a/src/ext_mod.erl
+++ b/src/ext_mod.erl
@@ -29,7 +29,7 @@
 -behaviour(gen_server).
 -author("Christophe Romain <christophe.romain@process-one.net>").
 
--export([start_link/0, update/0, check/1,
+-export([start_link/0, update/0, check/1, pre_start/0,
          available_command/0, available/0, available/1,
          installed_command/0, installed/0, installed/1,
          install/1, uninstall/1, upgrade/0, upgrade/1,
@@ -49,14 +49,16 @@
 
 -record(state, {}).
 
+pre_start() ->
+    [code:add_patha(module_ebin_dir(Module))
+     || {Module, _} <- installed()],
+    p1_http:start().
+
 start_link() ->
     gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
 
 init([]) ->
     process_flag(trap_exit, true),
-    [code:add_patha(module_ebin_dir(Module))
-     || {Module, _} <- installed()],
-    p1_http:start(),
     ejabberd_commands:register_commands(get_commands_spec()),
     {ok, #state{}}.
 
```

**Comment by zinid** [comment] 2017-04-19 15:00
In this patch we start ext_mod from two places now, which is crap, I don't like it, we got tons of problems back in the time with such approach.
Are there better solutions? I'm trying hard to eliminate all this crap, yet we're still adding new.

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-19 16:43
@badlop @zinid The above patch does not solved the problem. I am still getting the same error

> unknown option 'auth_opts' will be likely ignored

**Comment by badlop** [comment] 2017-04-20 10:54
Ok, let's forget that patch because it makes ejabberd dirtier... and doesn't solve the problem.

Let's try this alternative:
1. Start ejabberd
2. Run as usual: ejabberdctl module_install ejabberd_auth_http
3. Copy ejabberd_auth_http.beam from $/.ejabberd-modules/ejabberd_auth_http/ebin into the directory where you have all the other ejabberd *.beam files
4. Configure as usual ejabberd.yml to use auth_http
5. Restart ejabberd

In my tests, the error about the options doesn't appear, but still ejabberd doesn't fully start.

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-20 11:20
@badlop I did not understand  **into the directory where you have all the other ejabberd *.beam files**
I have a lib directory with different folders containing .beam files in ejabberd installation directory 
Can you please tell me the exact folder to copy files into. 
My ejabberd is installed in /opt/ejabberd/17.04 with following folders inside 
**bin  conf  database  doc  lib  logs**

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-20 11:39
In my /opt/ejabberd-17.04/lib directory i see lots of .beam files but not sure where to put this beam file into 

Here is my /opt/ejabberd-17.04/lib directory
```
├── asn1-4.0.2
│   ├── doc
│   ├── ebin
│   ├── examples
│   └── priv
│       └── lib
├── cache_tab-1.0.7
│   └── ebin
├── cean-2.1
│   └── ebin
├── compiler-6.0.3
│   └── ebin
├── crypto-3.6.3
│   ├── ebin
│   └── priv
│       ├── lib
│       └── obj
├── ejabberd-17.04
│   ├── ebin
│   ├── include
│   └── priv
│       ├── bin
│       ├── msgs
│       └── sql
├── elixir-1.2.6
│   └── ebin
├── eredis-1.0.8
│   ├── ebin
│   ├── include
│   └── priv
├── erts-7.3
│   └── ebin
├── esip-1.0.11
│   ├── ebin
│   ├── include
│   └── priv
│       └── lib
├── eunit-2.2.13
│   ├── doc
│   ├── ebin
│   ├── examples
│   └── include
├── ezlib-1.0.2
│   ├── ebin
│   └── priv
│       └── lib
├── fast_tls-1.0.11
│   ├── ebin
│   └── priv
│       └── lib
├── fast_xml-1.1.21
│   ├── ebin
│   ├── include
│   └── priv
│       └── lib
├── fast_yaml-1.0.9
│   ├── ebin
│   └── priv
│       └── lib
├── goldrush-0.1.8
│   ├── ebin
│   └── priv
├── hamcrest-0.3.0-basho
│   ├── ebin
│   └── include
├── hipe-3.15
│   ├── cerl
│   ├── ebin
│   ├── flow
│   ├── icode
│   ├── llvm
│   ├── main
│   ├── misc
│   ├── rtl
│   └── util
├── iconv-1.0.4
│   ├── ebin
│   └── priv
│       └── lib
├── inets-6.2
│   ├── doc
│   ├── ebin
│   ├── examples
│   │   ├── httpd_load_test
│   │   └── server_root
│   │       ├── auth
│   │       ├── cgi-bin
│   │       ├── conf
│   │       ├── htdocs
│   │       │   ├── misc
│   │       │   ├── mnesia_open
│   │       │   ├── mnesia_secret
│   │       │   │   └── top_secret
│   │       │   ├── open
│   │       │   └── secret
│   │       │       └── top_secret
│   │       ├── icons
│   │       ├── logs
│   │       └── ssl
│   ├── include
│   └── priv
│       └── bin
├── jiffy-0.14.8
│   ├── ebin
│   └── priv
├── kernel-4.2
│   ├── doc
│   ├── ebin
│   ├── examples
│   │   └── uds_dist
│   │       ├── c_src
│   │       ├── ebin
│   │       ├── priv
│   │       └── src
│   └── include
├── lager-3.2.1
│   ├── ebin
│   ├── include
│   └── priv
├── linux-x86_64
├── luerl-1
│   └── ebin
├── meck-0.8.2
│   └── ebin
├── mnesia-4.13.3
│   ├── doc
│   ├── ebin
│   ├── examples
│   │   └── bench
│   └── include
├── odbc-2.11.1
│   ├── ebin
│   ├── include
│   └── priv
│       ├── bin
│       └── obj
├── os_mon-2.4
│   ├── ebin
│   ├── include
│   ├── mibs
│   │   └── v1
│   └── priv
│       ├── bin
│       └── mibs
├── p1_mysql-1.0.2
│   ├── ebin
│   └── include
├── p1_oauth2-0.6.1
│   └── ebin
├── p1_pgsql-1.1.2
│   └── ebin
├── p1_utils-1.0.8
│   ├── ebin
│   └── include
├── parsetools-2.1.1
│   ├── ebin
│   └── include
├── protobuffs-0.8.4
│   └── ebin
├── public_key-1.1.1
│   ├── asn1
│   ├── ebin
│   ├── include
│   └── priv
├── rebar_elixir_plugin-0.1.0
│   └── ebin
├── riakc-2.4.1
│   ├── ebin
│   ├── include
│   └── priv
├── riak_pb-2.1.4.1
│   ├── ebin
│   └── include
├── runtime_tools-1.9.3
│   ├── doc
│   ├── ebin
│   ├── examples
│   ├── include
│   └── priv
│       ├── lib
│       └── obj
├── sasl-2.7
│   ├── doc
│   ├── ebin
│   ├── examples
│   │   ├── ebin
│   │   └── src
│   └── include
├── sqlite3-1.1.5
│   ├── ebin
│   ├── include
│   └── priv
├── ssl-7.3
│   ├── doc
│   ├── ebin
│   └── examples
│       ├── certs
│       │   └── etc
│       │       ├── client
│       │       ├── erlangCA
│       │       ├── otpCA
│       │       └── server
│       ├── ebin
│       └── src
├── stdlib-2.8
│   ├── doc
│   ├── ebin
│   ├── examples
│   └── include
├── stringprep-1.0.8
│   ├── ebin
│   └── priv
│       └── lib
├── stun-1.0.10
│   ├── ebin
│   └── include
├── syntax_tools-1.7
│   ├── doc
│   ├── ebin
│   ├── examples
│   └── include
├── tools-2.8.3
│   ├── bin
│   ├── doc
│   ├── ebin
│   ├── examples
│   └── priv
│       └── bin
├── xmerl-1.3.10
│   ├── ebin
│   └── include
└── xmpp-1.1.9
    ├── ebin
    └── include
```
Please tell me where to put this .beam file into

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-20 13:37
@badlop Can you please tell me about the path to copy **.beam file** from ejabberd_auth_http module ebin directory?

**Comment by badlop** [comment] 2017-04-20 13:55
In your case, /opt/ejabberd-17.04/lib/ejabberd-17.04/ebin because that dir contains all the ejabberd_*.beam files, like ejabberd_http.beam ...

**Comment by Hassnain-Raza-Alvi** [comment] 2017-04-24 08:18
@badlop By doing that change the warning is not appearing but i cannot access 
admin panel at localhost:5280/admin and if i connect an XMPP client it does not work i-e it never actually come for authentication to ejabberd-auth

**Comment by jalstrup-spok** [comment] 2017-05-31 15:04
Any update on this?

**Comment by dorsegal** [comment] 2017-06-28 14:30
Hi,

I'm using ejabberd 17.4 and did everything by the book but fro some reason ejabberd is not coming up.

Starting ejabberd...
14:29:20.944 [info] Application lager started on node ejabberd@f4a2325f776f
14:29:20.956 [info] Application crypto started on node ejabberd@f4a2325f776f
14:29:20.972 [info] Application sasl started on node ejabberd@f4a2325f776f
14:29:20.992 [info] Application asn1 started on node ejabberd@f4a2325f776f
14:29:20.992 [info] Application public_key started on node ejabberd@f4a2325f776f
14:29:21.015 [info] Application ssl started on node ejabberd@f4a2325f776f
14:29:21.028 [info] Application fast_yaml started on node ejabberd@f4a2325f776f
14:29:21.045 [info] Application fast_tls started on node ejabberd@f4a2325f776f
14:29:21.061 [info] Application fast_xml started on node ejabberd@f4a2325f776f
14:29:21.071 [info] Application p1_utils started on node ejabberd@f4a2325f776f
14:29:21.076 [info] Application stringprep started on node ejabberd@f4a2325f776f
14:29:21.077 [info] Application xmpp started on node ejabberd@f4a2325f776f
14:29:21.089 [info] Application cache_tab started on node ejabberd@f4a2325f776f
14:29:21.108 [info] Application elixir started on node ejabberd@f4a2325f776f
14:29:21.314 [info] Application mnesia started on node ejabberd@f4a2325f776f
14:29:22.410 [info] FQDN used to check DIGEST-MD5 SASL authentication: f4a2325f776f
14:29:23.539 [info] Application inets started on node ejabberd@f4a2325f776f
14:29:24.420 [info] Application iconv started on node ejabberd@f4a2325f776f

hangs and then restart with no errors

**Comment by thePhilGuy** [comment] 2017-08-04 17:34
Any update on this issue? I am running ejabberd 17.06-12 and also running into the same issue where ejabberd complains about `auth_opts` being invalid:
`2017-08-04 15:44:31.613 [error] <0.787.0>@ejabberd_config:validate_opts:1022 unknown option 'auth_opts' will be likely ignored`
And then ejabberd hangs and fails to start. This happens even after copying the .beam files over.

**Comment by vmichnowicz** [comment] 2017-08-11 23:07
I'm running into the same issues here. I'm going to try an older version of ejabberd and see if I have any luck.

**Comment by badlop** [comment] 2017-08-14 14:28
> I'm using ejabberd 17.4 and did everything by the book but fro some reason ejabberd is not coming up.

Oh, problem confirmed: since the change in ejabberd start process some weeks/months ago, ejabberd_auth_http does not allow ejabberd to start fully and correctly, regardless of how it's installed, copied, etc. I'll have to check its code.

**Comment by badlop** [comment] 2017-08-15 10:29
> ejabberd_auth_http does not allow ejabberd to start fully and correctly, regardless of how it's installed, copied, etc. I'll have to check its code.

I think I've fixed that starting problem, can you please confirm?

There's still the problem that this module requires manual installation, I suspect that cannot be solved.

**Comment by cromain** [comment] 2018-01-03 15:27
@badlop i think we can close this issue, right ? please do.

**Closed** 2018-01-10 15:30 UTC

**Comment by damirci** [comment] 2018-11-21 12:55
The problem still exists and I'm using version 18.09 on windows. 
Error log is: 

> @ejabberd_config:validate_opts: Unknown option 'auth_opts'

**Comment by badlop** [comment] 2018-11-21 13:35
Then open a new ticket, describe your setup, and how you install ejabberd and the module.
